name: notes_crud_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path: ^1.8.3
  path_provider: ^2.1.3
  file_picker: ^10.2.0
  flutter_quill: ^11.4.1
  flutter_quill_extensions: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # DITAMBAHKAN: Bagian untuk mendaftarkan aset (gambar, font, dll.)
  assets:
    - assets/